### ISSUE TITLE
Some misses of Example of use

### ISSUE THREAD

**Issue by dotchang** [ghiouar/OfxDynamixel#1]
1. arguments of ofDynamixel constructor
ofDynamixel * dynamixel = new ofDynamixel(ID, portConnexion);
there are no 2 argument definitions.
maybe,
ofDynamixel::ofDynamixel(int id, ofConnexion * portHandler, int position_min, int position_max)

2. print functions 
for example,
printf(dynamixel->getControlTable()->getID());
is 
printf("%d\n", dynamixel->getControlTable()->getID());

3. include pathes
In default settings, "ofxDynamixel/src" is not in the scope.
#include "ofxDynamixel/src/ofConnexion.h";
#include "ofxDynamixel/src/ofDynamixel.h";
maybe,
#include "ofConnexion.h";
#include "ofDynamixel.h";

**Comment by dotchang** [comment]
4. succes = portConnexion->setBaudRate(57142);
is
succes = portConnexion->setBaudRate(BAUDRATE);

**Comment by ghiouar** [comment]
Thanks! Updated
